# air.conf
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  delay = 1000 # delay to trigger build (ms)
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
